apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegen
namePrefix: dev-
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jcy0308/aegen-be
  newTag: 2cb708992585fa1d415533131f2eff6604419439
- name: jcy0308/aegen-fe
  newTag: e032143379daad8f8109ae198161b1f421f09173
