apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegen
namePrefix: dev-
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jcy0308/aegen-be
  newTag: d8dafa4dcfc0862e2d42f1149c8801103e5947a7
- name: jcy0308/aegen-fe
  newTag: 91dd8a926e06a218fd215a2eb0e9d5f562617411
