apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegen
namePrefix: dev-
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jcy0308/aegen-be
  newTag: 184d5420323b331c91d5020ac3fcfa0410c4c6ad
- name: jcy0308/aegen-fe
  newTag: 6e59541ab9d3a10da25014a8efe9775f874f626b
