apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegen
namePrefix: dev-
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jcy0308/aegen-be
  newTag: eb6c984acc73d4139eb07dd54e27731e000572ca
- name: jcy0308/aegen-fe
  newTag: baa5a56c8a359af24a3654c962295168a92e041f
