apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegen
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jcy0308/aegen
  newTag: 0eaafb1a17f8213ef1e0b4ecf5efd94335e73830
- name: jcy0308/aegen-be
  newTag: 4908a835a3ec6340298e999f787beb67d70fda3d
