apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegen
namePrefix: dev-
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jcy0308/aegen-be
  newTag: 297760b0358773fec07261a3ab60e400ba20a31e
- name: jcy0308/aegen-fe
  newTag: baa5a56c8a359af24a3654c962295168a92e041f
