apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegen
namePrefix: dev-
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jcy0308/aegen-be
  newTag: 266aa77195ad0f3ae8c618f30501bb7f67a34061
- name: jcy0308/aegen-fe
  newTag: 6e59541ab9d3a10da25014a8efe9775f874f626b
