apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegen
namePrefix: dev-
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jcy0308/aegen-be
  newTag: ccb27fa1ce71a126b7ca2c58fde044bae5a91c85
- name: jcy0308/aegen-fe
  newTag: baa5a56c8a359af24a3654c962295168a92e041f
