apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aegen
namePrefix: dev-
patchesStrategicMerge:
- ingress.yaml
resources:
- ../../base
- namespace.yaml
images:
- name: jcy0308/aegen-be
  newTag: 297760b0358773fec07261a3ab60e400ba20a31e
- name: jcy0308/aegen-fe
  newTag: 30baa740ee4f64f461d5522b916d31edd77ad510
